"""Short-term memory document (MEMORY_SPEC §2.1).

STM is a markdown file ``short_term.md`` made up of sections. Each section
begins with a level-2 header carrying timestamp range and topic:

    ## [2026-05-22T14:00:00+08:00 – 2026-05-22T15:30:00+08:00] portfolio rebalance
    [topics: portfolio, rebalancing, AAPL]

    Discussed Q1 portfolio drift; agent identified AAPL overweight...

The header is machine-parseable so the recall index can locate sections by
topic / date. Body text is free-form for the LLM.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from .paths import short_term_path
from .storage import atomic_write_text, file_lock

# ``## [<iso ts> – <iso ts>] <topic>``. The middle separator can be an en-dash
# (U+2013) or the ASCII ``--`` — we accept both on read and write the en-dash
# to match MEMORY_SPEC.
_HEADER_RE = re.compile(
    r"^##\s+\[(?P<start>[^\]\s]+)\s*[–\-]+\s*(?P<end>[^\]\s]+)\]\s+(?P<topic>.+?)\s*$"  # noqa: RUF001
)
_TOPICS_RE = re.compile(r"^\[topics:\s*(?P<topics>.*?)\s*\]\s*$")


@dataclass(slots=True)
class STMSection:
    ts_start: str
    ts_end: str
    topic: str
    topics: list[str] = field(default_factory=list)
    body: str = ""

    def header(self) -> str:
        return f"## [{self.ts_start} – {self.ts_end}] {self.topic}"  # noqa: RUF001

    def render(self) -> str:
        parts = [self.header()]
        if self.topics:
            parts.append("[topics: " + ", ".join(self.topics) + "]")
        parts.append("")  # blank line between header and body
        parts.append(self.body.rstrip("\n"))
        return "\n".join(parts) + "\n"


def parse(text: str) -> list[STMSection]:
    sections: list[STMSection] = []
    current: STMSection | None = None
    body_lines: list[str] = []

    def _flush() -> None:
        nonlocal current
        if current is not None:
            current.body = "\n".join(body_lines).strip("\n")
            sections.append(current)
        body_lines.clear()

    for raw_line in text.splitlines():
        m = _HEADER_RE.match(raw_line)
        if m:
            _flush()
            current = STMSection(
                ts_start=m.group("start").strip(),
                ts_end=m.group("end").strip(),
                topic=m.group("topic").strip(),
            )
            continue
        if current is None:
            # Lines before the first header are dropped — STM is fully
            # machine-generated by compaction, so anything outside a section
            # is recovery debris.
            continue
        tm = _TOPICS_RE.match(raw_line)
        if tm and not current.topics and not body_lines:
            current.topics = [t.strip() for t in tm.group("topics").split(",") if t.strip()]
            continue
        body_lines.append(raw_line)

    _flush()
    return sections


def render(sections: list[STMSection]) -> str:
    if not sections:
        return ""
    return "\n".join(s.render() for s in sections)


# ── Store ───────────────────────────────────────────────────────────────────


class STMStore:
    """File-backed STM rooted at one eonlet's ``memory/`` directory."""

    def __init__(self, memory_dir: Path) -> None:
        self._path = short_term_path(memory_dir)

    @property
    def path(self) -> Path:
        return self._path

    def exists(self) -> bool:
        return self._path.exists()

    async def read(self) -> list[STMSection]:
        async with file_lock(self._path):
            return self._read_sync()

    def _read_sync(self) -> list[STMSection]:
        if not self._path.exists():
            return []
        return parse(self._path.read_text(encoding="utf-8"))

    async def read_raw(self) -> str:
        """Return the file body verbatim — for context injection."""
        async with file_lock(self._path):
            if not self._path.exists():
                return ""
            return self._path.read_text(encoding="utf-8")

    async def append_sections(self, new_sections: list[STMSection]) -> None:
        async with file_lock(self._path):
            existing = self._read_sync()
            atomic_write_text(self._path, render(existing + new_sections))

    async def replace(self, sections: list[STMSection]) -> None:
        """Rewrite the file with exactly ``sections``."""
        async with file_lock(self._path):
            atomic_write_text(self._path, render(sections))
